### ISSUE TITLE
Add Error Labels for all Controls

### ISSUE THREAD

**Issue by MRSessions** [MRSessions/UOPLTC#1]
Error labels for all input fields need to be created and assigned properly

**Comment by William-Bachman** [comment]
I am attempting to take this but it will not allow me to assign it to myself

**Comment by MRSessions** [comment]
Some of the error labels are now there.
Still need to add a couple more
Some validations need to be complete for other fields
Label forecolor needs to be red
Label visibility needs to be set false on form load

**Comment by MRSessions** [comment]
All error labels have been added
