### ISSUE TITLE
Customer Join Date for when customer joined

### ISSUE THREAD

**Issue by MRSessions** [MRSessions/UOPLTC#8]
a. Dummy data will be added to the database before submission that will include this
b. For new users, this field should be auto set upon clearing the fields to add a new user

**Comment by jmk61482** [comment]
I added the coding for this section to provide current date as new entry is being created but unfortunately cannot sync still.  Copied and pasted into team assignment discussion.

**Comment by MRSessions** [comment]
Resolving this as this is already implemented, and this field is going to be read-only

**Comment by MRSessions** [comment]
Completed
